apiVersion: apps/v1
kind: Deployment
metadata:
  name: infrastructure-management   # giving the label infrastructure-management, to help with object referencing (necessary for load balancing)
spec:
  replicas: 1               # creating a few replicas of the same container
  selector:
    matchLabels:
      service: infrastructure-management
  template:
    metadata:
      labels:
        service: infrastructure-management
    spec:
      containers:
      - name: infrastructure-management
        image: 399029391937.dkr.ecr.ap-south-1.amazonaws.com/acaas/infrastructure-management:$IMAGETAG          # added placeholder which Jenkins will update pre-deploy.
        imagePullPolicy: Always
        livenessProbe:
          initialDelaySeconds: 5   # start probing after some time (enough time to boot)
          periodSeconds: 30         # repeat the health check periodically
          httpGet:
            path: /infrastructureManagement/health # check the health of the server
            port: 8030
        resources:
          requests:
            memory: "128Mi"   # memory request constraints on dev are restrictive.
            cpu: "250m"
          limits:
            memory: "256Mi"   # overprovision on prod to prevent out of memory issues. (kubernetes restarts out of memory pods)
            cpu: "500m"
        ports:
        - containerPort: 8030
        envFrom:              # obtain the ENV vars from a k8s secret
          - secretRef:
              name: infrastructure-management
      nodeSelector:
        environment: test

---

apiVersion: v1
kind: Service
metadata:
  name: infrastructure-management
spec:
  ports:
    - port: 8030
      protocol: TCP
  type: NodePort
  selector:
    service: infrastructure-management

---

apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler     # using HPA to horizontally scale the services on load.
metadata:
  name: infrastructure-management
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: infrastructure-management       # details of the deployment to autoscale
  minReplicas: 1
  maxReplicas: 2
  metrics:
  - type: Resource                # monitoring CPU usage metric to autoscale
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
