apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: k8s-spintly  # this will be used to name the EC2 instances in the cluster
  region: ap-south-1 # request to use the ap-south-1 (Mumbai) region (for Indian audiences)

managedNodeGroups:
  - name: ng-t3a-autoscale
    desiredCapacity: 2
    maxSize: 4
    instancesDistribution: # this performs an optimised distribution
      maxPrice: 0.1 # hourly pricing in dollars ($0.1*24*30 = $72/mo)
      instanceTypes: ["t3a.small", "t3a.medium"] # trying burstables right now, will switch to "m5.large" if it benefits in cost.
      onDemandBaseCapacity: 0 # no reserved on-demand requirements
      onDemandPercentageAboveBaseCapacity: 50 # 50% on demand, 50% spot instances. Set 0 for 100% spot instances.
      iam:
        withAddonPolicies:
          autoScaler: true
    # ssh: # use existing EC2 key
    #   publicKeyName: for-eks
# cloudWatch:
#   clusterLogging:
#     enableTypes: ["api", "audit", "authenticator"]