apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: k8s-spintly  # this will be used to name the EC2 instances in the cluster
  region: ap-south-1 # request to use the ap-south-1 (Mumbai) region (for Indian audiences)

managedNodeGroups:
  - name: ng-t3a-medium
    labels: { environment: "production", instances: "t3a.medium" }
    desiredCapacity: 2  # setting up a nodegroup with fixed instances.
    maxSize: 3
    instanceType: "t3a.medium"